import { awscdk, javascript, JsonFile } from 'projen';

const cdkVersion = '2.91.0';
const project = new awscdk.AwsCdkConstructLibrary({
   author: 'New Relic',
   authorAddress: 'https://newrelic.com',
   cdkVersion,
   defaultReleaseBranch: 'main',
   jsiiVersion: '~5.0.0',
   name: '@newrelic/cdk-l2-dashboards',
   projenrcTs: true,
   repositoryUrl: 'https://github.com/newrelic-experimental/cdk-l2-dashboards.git',
   description: 'AWS CDK Construct Library for New Relic Dashboards. Generated by projen & codegen.',
   license: 'Apache-2.0',
   deps: [
      'constructs',
      'graphql', // codegen
      'graphql-request', // codegen
      '@graphql-typed-document-node/core', // codegen
   ],
   devDeps: [
      'esbuild',
      'constructs',
      // Begin codegen
      '@graphql-codegen/cli',
      'typescript',
      '@graphql-codegen/introspection',
      '@graphql-codegen/client-preset',
      '@graphql-codegen/typescript-graphql-request',
      // End codegen
   ],
   stability: 'experimental',
   gitignore: [
      '.idea',
      'scratch',
      'graphql.config.yml',
      'cdk.out',
      'package-lock.json',
      'codegen.ts',
      'progen',
      'codegen',
   ],

   keywords: [
      'cdk',
      'aws-cdk',
      'awscdk',
      'cloudformation',
      'cfn',
      'extensions',
      'constructs',
      'cfn-resources',
      'cloudformation-registry',
      'l2',
      'newrelic',
      'new-relic',
   ],
   npmAccess: javascript.NpmAccess.PUBLIC,
   majorVersion: 1,
   docgen: true,
   releaseToNpm: true,
});

new JsonFile(project, 'cdk.json', {
   obj: {
      app: 'npx ts-node --prefer-ts-exts src/integ.default.ts',
   },
});

// Begin codegen
project?.addScripts({
   codegen: 'graphql-codegen --config codegen.ts',
});
project?.eslint?.addIgnorePattern('codegen.ts');
project?.tsconfigDev.addInclude('codegen.ts');
// End codegen

project?.eslint?.addRules({
   '@typescript-eslint/indent': ['error', 3],
   'no-trailing-spaces': ['error', { skipBlankLines: true }],
   'max-len': ['error', { code: 240 }],
});

// ALWAYS LAST!
project.synth();
